### PR TITLE
27 new minion gatherer

### PR DESCRIPTION
**Pull request by jpw1991**
## NecroNeck Gatherer & Armor Fix

This adds the NecroNeck Gatherer minion, but without a player-way to instantiate it. It must be instantiated with `spawn ChebGonaz_NecroNeck` in the terminal.

The point of the NecroNeck Gatherer is not to fight, but just to wander around and gather up all the stuff lying on the floor everywhere. It can also be used as a packmule. Although it is slow, weak, and dumb.

### NecroNeck Gatherer

- [ ] spawns in with `spawn ChebGonaz_NecroNeck` ?
- [ ] container can be opened by interacting with it (E key, by default)?
- [ ] items within container persist between sessions?
- [ ] necroneck vacuums items up all over the floor?
- [ ] items collected off the floor are collected correctly? (same amount, same type, etc)
- [ ] when the necroneck is killed, it should drop its items as a cargo crate (like a destroyed ship)

### Armor

Armor values are now taken into account. You can check the log when a skeleton gets hit and it should spit 0 for unarmored skeletons and higher numbers for armored ones. Ensure that:

- [ ] armor values start at 0 for unarmored, then progress higher for each type
- [ ] try to judge whether the defence increase is worth it. If it isn't, we may need to buff it further via a multiplier
- [ ] ensure that after logging out and coming back in the armor values are remembered (currently, they are not. I'll try to fix that tomorrow)

Log output to look for: `[Info   :FriendlySkeletonWand.CharacterGetDamageModifiersPatch] ChebGonaz_SkeletonWarriorTier3(Clone) applied body armor 0`

### Creature

image

### Container

image

### Container Drop

image

### CODE REVIEW

**Comment by Dracbjorn** [comment]
I will test this tonight.  Couple suggestions though:

- Make neck's container size customizable via a server config.  I believe you just set `container.m_height` for rows and `container.m_width` for columns.
- If there is a multiplier we can set for armor values, lets expose that as well.  That way players who have a server configured that does significantly more damage can tweak that as needed for balance.

**Comment by Dracbjorn** [comment]
Also, if we can change the name of the Neck....I think "Neckro" is just too fitting.

**Comment by jpw1991** [comment]
> Make neck's container size customizable via a server config. I believe you just set container.m_height for rows and container.m_width for columns.

Yes it should work. I'll try

**Comment by Dracbjorn** [comment]
# Test Results

### NecroNeck Gatherer

- [x] spawns in with `spawn ChebGonaz_NecroNeck` ?
- [x] container can be opened by interacting with it (E key, by default)?
- [ ] items within container persist between sessions?
- [x] necroneck vacuums items up all over the floor?
- [x] items collected off the floor are collected correctly? (same amount, same type, etc)
- [x] when the necroneck is killed, it should drop its items as a cargo crate (like a destroyed ship)

### Armor

Armor values are now taken into account. You can check the log when a skeleton gets hit and it should spit 0 for unarmored skeletons and higher numbers for armored ones. Ensure that:

- [x] armor values start at 0 for unarmored, then progress higher for each type
- [x] try to judge whether the defence increase is worth it. If it isn't, we may need to buff it further via a multiplier
- [ ] ensure that after logging out and coming back in the armor values are remembered (currently, they are not. I'll try to fix that tomorrow)

**Comment by jpw1991** [comment]
> # Test Results
> ### NecroNeck Gatherer
> * [x]  spawns in with `spawn ChebGonaz_NecroNeck` ?
> * [x]  container can be opened by interacting with it (E key, by default)?
> * [x]  items within container persist between sessions?
> * [x]  necroneck vacuums items up all over the floor?
> * [x]  items collected off the floor are collected correctly? (same amount, same type, etc)
> * [x]  when the necroneck is killed, it should drop its items as a cargo crate (like a destroyed ship)
> 
> ### Armor
> Armor values are now taken into account. You can check the log when a skeleton gets hit and it should spit 0 for unarmored skeletons and higher numbers for armored ones. Ensure that:
> 
> * [x]  armor values start at 0 for unarmored, then progress higher for each type
> * [x]  try to judge whether the defence increase is worth it. If it isn't, we may need to buff it further via a multiplier
> * [ ]  ensure that after logging out and coming back in the armor values are remembered (currently, they are not. I'll try to fix that tomorrow)

Thanks. I will merge and fix the final point at a later date

**Pull request merged**
